### ISSUE TITLE
document the data and code sharing

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/meg-hackathon#2]
I created an initial folder for the data and code sharing discussion that we had and added a PowerPoint version (as pptx and bitmap) of the state-change diagram that I made in the online meeting. 

Please add the other notes that we made to the README file.

**Comment by johalgermissen** [comment]
@mcpiastra did  the initial formating and I restructured things a bit (headers) and added some links to external webpages (e.g. zenodo, DR FAQ).
Can you have a brief look if nothing is blatantly wrong? 
Any suggestions for things we might still add?
