### ISSUE TITLE
Document strategies and technology for hybrid meetings

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/meg-hackathon#5]
This Monday we had the first hybrid MEG/EEG meeting, with some people present in real life (IRL), and others present on zoom. We spent quite some time trying to figure out what works best for both the IRL and online attendees. In the hackathon tomorrow I plan to work on making a start with documenting the lessons learned.

**Comment by robertoostenveld** [comment]
I made a first implementation with https://github.com/Donders-Institute/meg-hackathon/blob/master/2021-08-26-hybrid-meeting/README.md

**Comment by schoffelen** [comment]
Already looks impressive!
